---
settings:
  name: NetApp data services
  platform: cloud
  search: console-relnotes,console-setup-admin,storage-management-cloud-volumes-ontap,storage-management-ontap-onprem,storage-management-azure-netapp-files,storage-management-fsx-ontap,storage-management-cloud-volumes-service-gcp,data-services-backup-recovery,data-services-copy-sync,data-services-classification,data-services-cloud-tiering,data-services-replication,console-automation,cloud-volumes-ontap-relnotes,storage-management-storagegrid,storage-management-e-series,storage-management-s3-storage,console-lifecycle-planning,console-license-subscriptions,storage-management-blob-storage,console-volume-caching,data-services-disaster-recovery,storage-management-blob-storage,storage-management-google-cloud-storage,netapp-automation,data-services-ransomware-protection,console-software-updates,console-alerts,workload-setup-admin,workload-fsx-ontap,workload-databases,workload-genai,workload-vmware
  internal:
    pdf_enabled: false
    lipi_enabled: true
  prod:
    pdf_enabled: false
    harmony_enabled: false
    lipi_enabled: false
  langs: pt-br,us-en,de-de,es-es,fr-fr,it-it,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Console NetApp
    url: "../console-setup-admin/index.html"
  - title: Gerenciamento de armazenamento
    url: "../storage-management-family/index.html"
  - title: Notas de lançamento
    url: "../console-relnotes/index.html"
  - title: Backup e Recuperação
    url: "../data-services-backup-recovery/index.html"
  - title: Camadas de nuvem
    url: "../data-services-cloud-tiering/index.html"
  - title: Copiar e sincronizar
    url: "../data-services-copy-sync/index.html"
  - title: Classificação de Dados
    url: "../data-services-classification/index.html"
  - title: Recuperação de desastres
    url: "../data-services-disaster-recovery/index.html"
  - title: Resiliência ao Ransomware
    url: "../data-services-ransomware-resilience/index.html"
  - title: Replicação
    url: "../data-services-replication/index.html"
  - title: Cache de volume
    url: "../data-services-volume-caching/index.html"
  - title: Cargas de trabalho
    url: "../workload-family"
