---
settings:
  name: NetApp data services
  platform: cloud
  search: console-alerts, storage-management-s3-storage, console-automation, storage-management-azure-netapp-files,
    data-services-backup-recovery, storage-management-blob-storage, data-services-data-classification,
    storage-management-cloud-volumes-ontap, storage-management-google-cloud-netapp-volumes,
    data-services-data-classification, data-services-copy-sync, active-iq, console-licenses-subscriptions,
    data-services-disaster-recovery, storage-management-e-series, console-lifecycle-planning,
    storage-management-fsx-ontap, storage-management-google-cloud-storage, storage-management-ontap-onprem,
    data-services-ransomware-resilience, console-relnotes,data-services-replication,
    console-setup-admin, console-software-updates, storage-management-storagegrid,
    data-services-cloud-tiering, console-volume-caching, workload-setup-admin,workload-fsx-ontap,workload-databases,workload-genai,workload-vmware,
    keystone-staas
  internal:
    pdf_enabled: false
    lipi_enabled: true
  prod:
    pdf_enabled: false
    harmony_enabled: false
    lipi_enabled: false
  langs: pt-br,us-en,de-de,es-es,fr-fr,it-it,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Console NetApp
    url: "../console-setup-admin/index.html"
  - title: Gerenciamento de armazenamento
    url: "../storage-management-family/index.html"
  - title: Notas de lançamento
    url: "../console-relnotes/index.html"
  - title: Backup e Recuperação
    url: "../data-services-backup-recovery/index.html"
  - title: Camadas de nuvem
    url: "../data-services-cloud-tiering/index.html"
  - title: Copiar e sincronizar
    url: "../data-services-copy-sync/index.html"
  - title: Classificação de Dados
    url: "../data-services-data-classification/index.html"
  - title: Recuperação de desastres
    url: "../data-services-disaster-recovery/index.html"
  - title: Resiliência ao Ransomware
    url: "../data-services-ransomware-resilience/index.html"
  - title: Replicação
    url: "../data-services-replication/index.html"
  - title: Cache de volume
    url: "../data-services-volume-caching/index.html"
  - title: Cargas de trabalho
    url: "../workload-family"
